services:
  app:
    container_name: image_pixels_colorize-api
    image: image_pixels_colorize-api:1.0.0
    build: .
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./output:/app/output

  db:
    container_name: pgdb-python
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
